apiVersion: v1
kind: Service
metadata:
  name: question-service
  labels:
    app: question-service
spec:
#  type: ClusterIP => should be this
  type: NodePort
  ports:
    - name: "question-service"
      port: 8082
      targetPort: 8082
      nodePort: 30082
  selector:
    app: question-service
