apiVersion: v1
kind: Service
metadata:
  name: question-ai-service
  labels:
    app: question-ai-service
spec:
#  type: ClusterIP => should be this
  type: NodePort
  ports:
    - name: "question-ai-service"
      port: 8083
      targetPort: 8083
      nodePort: 30083
  selector:
    app: question-ai-service
