apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  labels:
    app: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      name: question-service
      labels:
        app: question-service
    spec:
      containers:
        - name: quiz-question-service
          image: vectorit/quiz-question-service
          ports:
            - containerPort: 8082
              name: question-srv-p


