apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  labels:
    app: quiz-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      name: quiz-service
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-quiz-service
          image: vectorit/quiz-quiz-service
          ports:
            - containerPort: 8081
              name: quiz-srv-p


