apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  labels:
    app: quiz-service
spec:
  replicas: 1 # must be 1 because service and db are in same pod
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      name: quiz-service
      labels:
        app: quiz-service
    spec:
      containers:
        - name: postgres
          image: postgres:17.5-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: quizdb
          ports:
            - containerPort: 5432
              name: quiz-db-port
        - name: quiz-quiz-service
          image: vectorit/quiz-quiz-service
          ports:
            - containerPort: 8081
              name: quiz-srv-p


